name: Pull/Run Unit tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]
  workflow_call:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test E2E'
    steps:
      - uses: actions/checkout@v4
        with:
          repository: modbus2mqtt/modbus2mqtt.dev
          path: .
      - name: initialize environment for this
        id: init
        run: |
          gh auth status
          owner=""
          if [ "${{github.event.act.owner}}" != '' ]
          then
            owner="-o ${{github.event.act.owner}}"
          else
            owner="-o ${{github.repository_owner}}"
          fi
          echo "owner=$owner" >> "$GITHUB_OUTPUT"
          bin/pulls.py -p repositories.test.json  $owner init -b main 
          echo "syncpull =========="
          bin/pulls.py -p repositories.test.json $owner syncpull --pullrequest ${{github.event.pull_request.base.repo.name}}:${{github.event.number}} --pulltext "${{github.event.pull_request.body}}" pull${{github.event.pull_request.number}} 
          echo "install =========="
          bin/pulls.py -p repositories.test.json $owner dependencies local
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Run tests
        id: test
        run: |
          bin/pulls.py -p repositories.test.json -o ${{steps.init.outputs.owner}} testorwait ${{github.event.pull_request.base.repo.name}}:${{github.event.number}} "${{github.event.pull_request.body}}"  >> "$GITHUB_OUTPUT"
          if [ -d server/cypress/e2e ]
          then
             echo "runcypress=true"  >> "$GITHUB_OUTPUT"
          fi
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Packages and system services for e2e Tests
        if: ${{ (steps.test.outputs.type == 'testrunner' == true) && (steps.test.outputs.runcypress == 'true')  }} 
        run: server/cypress/servers/installPackages
      - name: Local services for e2e Tests
        if: ${{ (steps.test.outputs.type == 'testrunner' == true) && (steps.test.outputs.runcypress == 'true')  }} 
        run: server/cypress/servers/startRunningServers
      - name: Cypress run
        if: ${{ (steps.test.outputs.type == 'testrunner' == true) && (steps.test.outputs.runcypress == 'true')  }} 
        uses: cypress-io/github-action@v6
        with:
          working-directory: server
          install: false


       
      
